import {createOverlayMotionVariant} from "../shared/OverlayMotionTemplate.jsx";

const theme = {
  name: "Variant03StickerAlbum",
  title: {
    align: "center",
    decoration: "sprinkles",
    decorationColors: ["#ffcadf", "#d9ebff", "#ffe49f", "#d7f3e3"],
    decorationMarginTop: 12,
    fill: "linear-gradient(90deg, #ffb0c8 0%, #ffc98f 28%, #8fd2c8 58%, #9cbcf6 100%)",
    fillMode: "gradient",
    font: "pop-bold",
    fontMax: 112,
    fontMin: 78,
    fontScale: 0.078,
    fontWeight: 700,
    kicker: null,
    kickerColor: "#fff3f6",
    kickerFont: "ui",
    kickerLetterSpacing: "0.10em",
    kickerShadow: "0 2px 10px rgba(0,0,0,0.28)",
    kickerSize: 16,
    letterSpacing: "0.012em",
    outlineColor: "rgba(92, 70, 78, 0.78)",
    position: "center",
    shadow: "0 10px 26px rgba(0,0,0,0.42)",
    strokeWidth: 0.9,
    subtitleColor: "#fffaf0",
    subtitleFont: "pop-bold",
    subtitleLetterSpacing: "0.02em",
    subtitleMax: 30,
    subtitleMin: 22,
    subtitleScale: 0.019,
    subtitleShadow: "0 5px 20px rgba(0,0,0,0.42)",
    topRatio: 0.075,
    widthMax: 1400,
  },
  credit: {
    align: "center",
    allowWide: true,
    anchor: "bottom",
    bottomRatio: 0.09,
    compactThreshold: 1180,
    eyebrowColor: "#ffe8f0",
    eyebrowFont: "ui",
    eyebrowLetterSpacing: "0.12em",
    eyebrowShadow: "0 2px 10px rgba(0,0,0,0.28)",
    eyebrowSize: 17,
    gridGap: 22,
    headingColor: "#fffdf6",
    headingFont: "pop-bold",
    headingGap: 18,
    headingLetterSpacing: "0.02em",
    headingMax: 42,
    headingMin: 32,
    headingScale: 0.026,
    headingShadow: "0 3px 16px rgba(0,0,0,0.32)",
    innerGap: 12,
    itemGap: 14,
    labelColor: "#ffe0db",
    labelFontSize: 15,
    labelLetterSpacing: "0.08em",
    labelShadow: "0 2px 10px rgba(0,0,0,0.26)",
    layout: "grid",
    marker: "dot",
    markerOutlineColor: "rgba(92, 70, 78, 0.78)",
    position: "center",
    sectionAccents: ["#9cccff", "#ffd58f", "#a9e3c5"],
    sectionFrame: "left-bar",
    sectionFrameWidth: 4,
    sectionTitleColor: "#fffdf8",
    sectionTitleFontSize: 24,
    sectionTitleLetterSpacing: "0.02em",
    sectionTitleShadow: "0 2px 12px rgba(0,0,0,0.28)",
    valueColor: "#ffffff",
    valueFont: "pop-bold",
    valueFontSize: 23,
    valueShadow: "0 3px 14px rgba(0,0,0,0.34)",
    valueWeight: 700,
    widthMax: 1260,
  },
};

export const Variant03StickerAlbum = createOverlayMotionVariant(theme);
