import {createOverlayMotionVariant} from "../shared/OverlayMotionTemplate.jsx";

const theme = {
  name: "Variant05ToyCatalog",
  title: {
    align: "left",
    decoration: "sprinkles",
    decorationColors: ["#d8ebff", "#ffe3a8", "#ffd6df", "#d7f2e1"],
    decorationMarginTop: 10,
    fill: "#fffdf8",
    fillMode: "solid",
    font: "pop-bold",
    fontMax: 102,
    fontMin: 70,
    fontScale: 0.070,
    fontWeight: 800,
    kicker: null,
    kickerColor: "#dbe6ff",
    kickerFont: "ui",
    kickerLetterSpacing: "0.14em",
    kickerShadow: "0 2px 10px rgba(0,0,0,0.26)",
    kickerSize: 15,
    letterSpacing: "0.02em",
    outlineColor: "rgba(84, 73, 67, 0.66)",
    position: "right",
    shadow: "0 8px 24px rgba(0,0,0,0.40)",
    strokeWidth: 0.5,
    subtitleColor: "#fff5ea",
    subtitleFont: "pop-bold",
    subtitleLetterSpacing: "0.02em",
    subtitleMax: 28,
    subtitleMin: 20,
    subtitleScale: 0.018,
    subtitleShadow: "0 5px 18px rgba(0,0,0,0.40)",
    topRatio: 0.08,
    widthMax: 1180,
  },
  credit: {
    align: "left",
    allowWide: true,
    anchor: "bottom",
    bottomRatio: 0.07,
    compactThreshold: 1200,
    eyebrowColor: "#ecf2ff",
    eyebrowFont: "ui",
    eyebrowLetterSpacing: "0.12em",
    eyebrowShadow: "0 2px 10px rgba(0,0,0,0.26)",
    eyebrowSize: 16,
    gridGap: 20,
    headingColor: "#fffefb",
    headingFont: "pop-bold",
    headingGap: 14,
    headingLetterSpacing: "0.02em",
    headingMax: 38,
    headingMin: 30,
    headingScale: 0.024,
    headingShadow: "0 3px 12px rgba(0,0,0,0.30)",
    innerGap: 10,
    itemGap: 12,
    labelColor: "#f0d6cd",
    labelFontSize: 14,
    labelLetterSpacing: "0.08em",
    labelShadow: "0 2px 10px rgba(0,0,0,0.24)",
    layout: "grid",
    marker: "long-line",
    markerOutlineColor: "rgba(84, 73, 67, 0.66)",
    position: "left",
    sectionAccents: ["#8cc0ff", "#ffd28a", "#a8ddc0"],
    sectionFrame: "top-line",
    sectionFrameWidth: 3,
    sectionTitleColor: "#ffffff",
    sectionTitleFontSize: 22,
    sectionTitleLetterSpacing: "0.03em",
    sectionTitleShadow: "0 2px 10px rgba(0,0,0,0.28)",
    valueColor: "#fffefc",
    valueFont: "pop-bold",
    valueFontSize: 22,
    valueShadow: "0 3px 12px rgba(0,0,0,0.32)",
    valueWeight: 800,
    widthMax: 1240,
  },
};

export const Variant05ToyCatalog = createOverlayMotionVariant(theme);
