import {createOverlayMotionVariant} from "../shared/OverlayMotionTemplate.jsx";

const theme = {
  name: "Variant02MilkBottleLabel",
  title: {
    align: "left",
    decoration: "line",
    decorationColors: ["#ff9f1c", "#ffe14d"],
    decorationMarginTop: 12,
    characterPalette: ["#ff5c9f", "#ff9f1c", "#ffe14d", "#21d88f", "#30b8ff"],
    fill: "linear-gradient(90deg, #ff9f1c 0%, #ffe14d 40%, #ff5ca8 100%)",
    fillMode: "per-character",
    font: "pop-bold",
    fontMax: 104,
    fontMin: 72,
    fontScale: 0.075,
    fontWeight: 700,
    kicker: null,
    kickerColor: "#ffe7b1",
    kickerFont: "ui",
    kickerLetterSpacing: "0.12em",
    kickerShadow: "0 2px 10px rgba(0,0,0,0.28)",
    kickerSize: 16,
    characterGap: 1,
    letterSpacing: "0.01em",
    outlineColor: "rgba(95, 78, 62, 0.72)",
    position: "left",
    shadow: "0 8px 24px rgba(0,0,0,0.42)",
    strokeWidth: 0.6,
    subtitleColor: "#fff7e7",
    subtitleFont: "pop-bold",
    subtitleLetterSpacing: "0.02em",
    subtitleMax: 28,
    subtitleMin: 20,
    subtitleScale: 0.018,
    subtitleShadow: "0 5px 18px rgba(0,0,0,0.40)",
    topRatio: 0.08,
    widthMax: 1280,
  },
  credit: {
    align: "left",
    allowWide: false,
    anchor: "bottom",
    bottomRatio: 0.08,
    compactThreshold: 1280,
    eyebrowColor: "#dbe9ff",
    eyebrowFont: "ui",
    eyebrowLetterSpacing: "0.12em",
    eyebrowShadow: "0 2px 10px rgba(0,0,0,0.28)",
    eyebrowSize: 17,
    gridGap: 20,
    headingColor: "#fffef7",
    headingFont: "pop-bold",
    headingGap: 16,
    headingLetterSpacing: "0.015em",
    headingMax: 40,
    headingMin: 30,
    headingScale: 0.024,
    headingShadow: "0 3px 14px rgba(0,0,0,0.30)",
    innerGap: 12,
    itemGap: 12,
    labelColor: "#ffd4c9",
    labelFontSize: 15,
    labelLetterSpacing: "0.10em",
    labelShadow: "0 2px 10px rgba(0,0,0,0.28)",
    layout: "stack",
    marker: "line",
    markerOutlineColor: "rgba(95, 78, 62, 0.72)",
    position: "left",
    sectionAccents: ["#26b7ff", "#ffb800", "#19db83"],
    sectionFrame: "left-bar",
    sectionFrameWidth: 4,
    sectionTitleColor: "#fffef8",
    sectionTitleFontSize: 23,
    sectionTitleLetterSpacing: "0.02em",
    sectionTitleShadow: "0 2px 12px rgba(0,0,0,0.28)",
    valueColor: "#ffffff",
    valueFont: "pop-bold",
    valueFontSize: 23,
    valueShadow: "0 3px 14px rgba(0,0,0,0.34)",
    valueWeight: 700,
    widthMax: 920,
  },
};

export const Variant02MilkBottleLabel = createOverlayMotionVariant(theme);
