import {createOverlayMotionVariant} from "../shared/OverlayMotionTemplate.jsx";

const theme = {
  name: "Variant01CharacterSheet",
  title: {
    align: "center",
    decoration: "dots",
    decorationColors: ["#d7ebff", "#ffe8b8", "#ffdce7", "#dff4e9"],
    decorationMarginTop: 14,
    fill: "linear-gradient(90deg, #f09aa8 0%, #f3c878 34%, #8fc4f1 68%, #b6a8ea 100%)",
    fillMode: "gradient",
    font: "pop-bold",
    fontMax: 118,
    fontMin: 82,
    fontScale: 0.082,
    fontWeight: 700,
    kicker: null,
    kickerColor: "#fff7e9",
    kickerFont: "ui",
    kickerLetterSpacing: "0.10em",
    kickerShadow: "0 2px 10px rgba(0,0,0,0.30)",
    kickerSize: 22,
    letterSpacing: "0.01em",
    outlineColor: "rgba(92, 70, 63, 0.86)",
    position: "center",
    shadow: "0 10px 28px rgba(0,0,0,0.42)",
    strokeWidth: 0.8,
    subtitleColor: "#fffdf8",
    subtitleFont: "pop-bold",
    subtitleLetterSpacing: "0.03em",
    subtitleMax: 34,
    subtitleMin: 24,
    subtitleScale: 0.021,
    subtitleShadow: "0 6px 22px rgba(0,0,0,0.44)",
    topRatio: 0.065,
    widthMax: 1500,
  },
  credit: {
    align: "center",
    allowWide: true,
    anchor: "bottom",
    bottomRatio: 0.10,
    compactThreshold: 1100,
    eyebrowColor: "#fff4e8",
    eyebrowFont: "ui",
    eyebrowLetterSpacing: "0.14em",
    eyebrowShadow: "0 2px 12px rgba(0,0,0,0.30)",
    eyebrowSize: 18,
    gridGap: 22,
    headingColor: "#fffef8",
    headingFont: "pop-bold",
    headingGap: 18,
    headingLetterSpacing: "0.02em",
    headingMax: 46,
    headingMin: 34,
    headingScale: 0.028,
    headingShadow: "0 4px 18px rgba(0,0,0,0.32)",
    innerGap: 10,
    itemGap: 14,
    labelColor: "#ffd8cf",
    labelFontSize: 16,
    labelLetterSpacing: "0.10em",
    labelShadow: "0 2px 10px rgba(0,0,0,0.28)",
    layout: "grid",
    marker: "dot",
    markerOutlineColor: "rgba(92, 70, 63, 0.78)",
    position: "center",
    sectionAccents: ["#8fc4f1", "#f3c878", "#a9dfc2"],
    sectionFrame: "top-line",
    sectionFrameWidth: 3,
    sectionTitleColor: "#fffef8",
    sectionTitleFontSize: 25,
    sectionTitleLetterSpacing: "0.02em",
    sectionTitleShadow: "0 3px 12px rgba(0,0,0,0.28)",
    valueColor: "#ffffff",
    valueFont: "pop-bold",
    valueFontSize: 24,
    valueShadow: "0 3px 14px rgba(0,0,0,0.34)",
    valueWeight: 700,
    widthMax: 1380,
  },
};

export const Variant01CharacterSheet = createOverlayMotionVariant(theme);
