import {createOverlayMotionVariant} from "../shared/OverlayMotionTemplate.jsx";

const theme = {
  name: "Variant04StorybookRibbon",
  title: {
    align: "left",
    decoration: "line",
    decorationColors: ["#f0d7a4", "#d9e6ff"],
    decorationMarginTop: 14,
    fill: "#fff9ef",
    fillMode: "solid",
    font: "pop-bold",
    fontMax: 106,
    fontMin: 72,
    fontScale: 0.076,
    fontWeight: 700,
    kicker: null,
    kickerColor: "#f2dfc4",
    kickerFont: "ui",
    kickerLetterSpacing: "0.12em",
    kickerShadow: "0 2px 10px rgba(0,0,0,0.28)",
    kickerSize: 15,
    letterSpacing: "0.03em",
    outlineColor: "rgba(88, 74, 61, 0.58)",
    position: "left",
    shadow: "0 8px 24px rgba(0,0,0,0.40)",
    strokeWidth: 0.4,
    subtitleColor: "#fff5e7",
    subtitleFont: "pop-bold",
    subtitleLetterSpacing: "0.02em",
    subtitleMax: 28,
    subtitleMin: 20,
    subtitleScale: 0.018,
    subtitleShadow: "0 5px 18px rgba(0,0,0,0.40)",
    topRatio: 0.09,
    widthMax: 1260,
  },
  credit: {
    align: "right",
    allowWide: false,
    anchor: "bottom",
    bottomRatio: 0.08,
    compactThreshold: 1080,
    eyebrowColor: "#efe0cc",
    eyebrowFont: "ui",
    eyebrowLetterSpacing: "0.12em",
    eyebrowShadow: "0 2px 10px rgba(0,0,0,0.26)",
    eyebrowSize: 16,
    gridGap: 18,
    headingColor: "#fff8ef",
    headingFont: "pop-bold",
    headingGap: 14,
    headingLetterSpacing: "0.02em",
    headingMax: 38,
    headingMin: 30,
    headingScale: 0.024,
    headingShadow: "0 3px 12px rgba(0,0,0,0.30)",
    innerGap: 10,
    itemGap: 12,
    labelColor: "#e6cec5",
    labelFontSize: 14,
    labelLetterSpacing: "0.08em",
    labelShadow: "0 2px 10px rgba(0,0,0,0.24)",
    layout: "stack",
    marker: "line",
    markerOutlineColor: "rgba(88, 74, 61, 0.58)",
    position: "right",
    sectionAccents: ["#a9d1ff", "#f2d09c", "#bbdfca"],
    sectionFrame: "top-line",
    sectionFrameWidth: 3,
    sectionTitleColor: "#fffaf3",
    sectionTitleFontSize: 22,
    sectionTitleLetterSpacing: "0.03em",
    sectionTitleShadow: "0 2px 10px rgba(0,0,0,0.26)",
    valueColor: "#fffefb",
    valueFont: "pop-bold",
    valueFontSize: 22,
    valueShadow: "0 3px 12px rgba(0,0,0,0.32)",
    valueWeight: 700,
    widthMax: 840,
  },
};

export const Variant04StorybookRibbon = createOverlayMotionVariant(theme);
